theme: jekyll-theme-midnight

name: Travis CI for Python

description: This is a short tutorial explaining the process of integrating Travis CI for an existing Python project, as well as showing users how to integrate its badge into users' GitHub repos.

author: Christopher Moussa

author_email: moussa1@llnl.gov

category_dir: /

permalink: pretty
